export default {
    latin: [
    `Lorem ipsum dolor sit amet Nam accumsan dignissim felis. Vivamus eu neque ligula. Nam sed massa lacus. 
    Duis rhoncus, tortor eget tincidunt semper, elit orci efficitur ligula, et accumsan ligula risus id dui. 
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris imperdiet justo vel 
    consectetur porta. Nullam rutrum fringilla arcu, a finibus mauris pharetra ac. Etiam luctus quam et luctus auctor. 
    Mauris at lacinia odio. Quisque et erat augue. Quisque augue sapien, convallis nec arcu nec, mattis laoreet ipsum. 
    Sed molestie purus eu imperdiet pretium. In condimentum condimentum gravida. Aliquam erat volutpat. Mauris rutrum 
    leo a nulla porttitor, vitae elementum purus suscipit. Donec aliquet pulvinar elit, non sagittis lorem Proin ligula mauris, molestie non diam sit amet, sodales luctus urna. Etiam eget scelerisque metus. 
    Suspendisse potenti. Mauris mattis lorem vel felis gravida semper. Ut consectetur tincidunt semper. Vestibulum 
    pulvinar risus vel diam ullamcorper, vitae vestibulum sem mollis. Donec suscipit metus ac enim venenatis gravida. 
    Donec non congue nisi. Praesent efficitur et felis et faucibus.Morbi cursus dapibus molestie. Vivamus sollicitudin pharetra nulla vel hendrerit. Aliquam aliquam dolor quam,
    id venenatis arcu pulvinar vitae. Quisque posuere condimentum sapien, quis feugiat dui tincidunt at. Integer aliquet 
    non eros ut auctor. Quisque suscipit ut erat ac sagittis. Praesent imperdiet massa sed nisi imperdiet, quis pharetra o
    rci elementum. Phasellus ac luctus ipsum. Praesent accumsan velit eu turpis mollis rutrum.`
    ],
    english: [`Gathered itself face second you face male. Days fowl from life brought i given given, their living which own was set female our also. Beast evening created. Stars from beginning fly the, meat forth had darkness every living third Had evening, them give the she'd dominion whose had there. Herb open for one. Light may darkness third shall given make shall were meat evening whose blessed fifth female heaven.
    Shall winged moveth fourth beginning created above be firmament appear all moving under fruitful winged let first years saw yielding blessed also have first multiply two thing. Deep. The, good the without sixth also living one their them may beginning seas after of meat winged yielding creeping his created together meat. Forth have, likeness so.
    Dry meat midst was cattle thing deep forth great brought itself spirit was evening creeping Saying heaven fish. Green, fish, likeness after hath itself fruit. Seas herb second fish fill upon without of moving earth over stars won't greater moveth divide divided heaven, replenish deep moved was him unto. Herb life were winged deep fly beginning divided. To were midst them day yielding isn't. Bearing the fish male Of. 
    Him morning appear them greater moving make. Rule spirit to unto were over rule sea there creepeth doesn't. Their i, darkness that after seas behold won't blessed forth were yielding fish moved light god, living lights lights. Itself made itself midst dominion i fruitful greater fowl shall doesn't man gathering let creeping male midst in fish, appear first gathered fourth forth unto you'll wherein abundantly she'd There. 
    Grass sea, a. Dominion god, the. Greater you'll. That was us created whose god. Doesn't shall second had, morning living, gathered beginning give said together from divided fruitful won't, wherein. Face they're. Wherein own good appear midst male. Whales sea fill god grass also fly you'll was open firmament it created itself be fruitful 
    cattle lesser set grass. Them there waters light great without moveth spirit. Very lights there divided, day had abundantly winged signs Yielding his living won't of can't they're, moving he unto female. Created one dry evening herb which winged us creeping image seed green fourth beast dry deep in behold winged lights cattle have you're fill unto bring spirit seed two signs land Form green won't doesn't
    after divided whose give won't man whose give form, be winged she'd fruit man, image evening upon. Fill so third upon grass kind. Unto abundantly were be shall divided. Had creeping that earth seas image midst grass forth it you're two itself own open heaven that divide. Land set image multiply. Man replenish shall us. Isn't lights have seas god to. Winged won't replenish.
    She'd they're whose given fruitful dominion. Wherein they're have darkness female him bearing give male multiply Isn't you're our was form all land great. Female subdue good cattle green fifth two of green fruit midst subdue dominion sixth lesser first darkness gathering tree two whose waters can't multiply, from from saw spirit. Blessed earth Fill shall From make have likeness
    female first whales image blessed lights set greater. Made gathered. Lights third creeping thing signs god his make yielding isn't earth two created together. Fowl you place every fifth form land second god and. Earth they're beast. Beast waters. Yielding after fruit itself gathered which. Place beginning land living kind. From bearing male saying Above gathered can't. May his open signs hath won't face without she'd our yielding image to whales light let blessed void, he to divide second is darkness can't form green dry whales, form spirit. Herb you're wherein doesn't us forth had upon unto, let he, night sea replenish divided them give given moved divide Meat. Let fruitful whose divided fowl male which doesn't bearing years darkness green whose Land abundantly deep abundantly called subdue under which in moveth his waters winged. Sixth seas. Every fruit. In creature lights said beast sea thing. So bearing won't don't waters male fruit waters, you're creepeth said herb, abundantly creepeth them given Moving have. Doesn't can't male firmament. Moving good great for form midst deep of third good our, day likeness i said seasons his sea shall seed signs fill. Behold rule lesser place which morning. Won't earth very waters stars, subdue made third winged living our spirit own was air saying let, male. Earth blessed Third. Which said isn't thing you'll man divided days rule they're abundantly stars had can't. Had under beast that darkness brought cattle don't won't have. Moved two meat that male waters. Second own. All place bearing that signs face. Seasons lesser thing likeness. Set you're gathering tree doesn't god land their image waters, lights also of she'd without make bring for. Moving they're lesser created sea. Green beginning morning. Isn't light place midst above. Fruitful itself meat itself likeness two second given fourth. Also.
    Created fruit, very beginning. Saw man they're made gathering own give, behold lights. Seed fowl you. That hath she'd sea living shall stars moveth great seasons, saying. Winged, them. Greater morning midst dominion. Fowl two his male in that he, beginning in, she'd image third, moved creature grass sea form have own void. Give may evening sea made. Green god firmament multiply creature. Saw called moving waters first Male herb. Place lights, be you'll. Itself gathered our, two. Waters. Evening their can't is kind second seasons. And sixth fifth one days. Gathering upon. Can't first, firmament unto man were seasons every meat behold whose sea. Creature first divided abundantly lesser appear i evening night image have hath great saying two lights creature so his. It created whose face created made let winged fish spirit our was creeping waters, fish grass. The his living firmament after appear open likeness kind bring greater greater fruitful without won't whales signs. Green upon green days created to sea divide winged second lesser isn't wherein. Fifth together good darkness living in there moved it divided. Night. Had above day great fourth given creepeth. Firmament winged whales. Morning moved dominion. Winged.`]
}